nacos:
  address: localhost:8848
  namespace: cb817249-a44e-4b34-bbc3-f7d9120574a1

dubbo:
  registry:
    address: nacos://${nacos.address}
    parameters[namespace]: ${nacos.namespace}
  consumer:
    timeout: 3000
#  provider:
#    host: 192.168.1.10

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/data-service-center?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  cloud:
    nacos:
      discovery:
        enabled: true
        # 注册地址，不需要写协议
        server-addr: ${nacos.address}
        # 命名空间，不同命名空间之间不能调用，用于环境隔离
        namespace: ${nacos.namespace}
        # 分组，不同分组之间不能调用，用于微服务之间的隔离
        group: DEFAULT_GROUP
        # 集群名称【有 BJ 和 NJ】，不同集群之间可以调用，但是在设计负载均衡策略的时候要避免跨机房集群调用
        # cluster-name: BJ
        # 元数据，让配置更加灵活
        # metadata:
        # 比如灰度发布时，可以跨集群调用，但是不能跨版本调用
        # version: v1
      config:
        enabled: true
        # 配置中心地址，不需要写协议
        server-addr: ${nacos.address}
        # 配置文件扩展后缀
        file-extension: yml
        # 命名空间，不同命名空间之间不能调用，用于环境隔离
        namespace: ${nacos.namespace}
        # 分组，不同分组之间不能调用，用于微服务之间的隔离
        group: DEFAULT_GROUP
        # 最大重试次数
        max-retry: 3
        refresh-enabled: true

logging:
  config: classpath:logback-local.xml
  level:
     com.data.service.center.dao.admin.mapper: debug