server:
  port: 8080
spring:
  profiles:
    active: local
  application:
    name: data-service-center
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      write-dates-as-timestamps: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  #加载nacos公共配置
  cloud:
    bootstrap:
      enabled: true
    nacos:
      config:
        extension-configs:
          - data-id: data-service-center.yml
            group: BIZ_GROUP
            refresh: true


dubbo:
  application:
    name: ${spring.application.name}
  consumer:
    retries: 0
    timeout: 1500
  provider:
    retries: 0
    timeout: 1500
  protocol:
    port: -1
    name: dubbo
    threads: 600
    threadpool: cached
    dispatcher: message
logging:
  level:
    com.study.application.mapper.*: debug
    #com.alibaba.nacos.client.*: off
    springfox.documentation.spring.web.readers.operation: off
management:
  server:
    port: 10880
  health:
    defaults:
      enabled: false

