spring:
  application:
    name: data-service-center
  profiles:
      active: dev
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8080
mybatis:
  mapper-locations:
    - classpath:/mappers/**/*.xml


logging:
  level:
    mapper: debug
    org:
      mybatis: debug
